version: 1
update_configs:
  # Keep package.json & package-lock.json up to date and perform weekly check on this.
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"

    # Apply reviewer(s) and label(s) to the PRs created by Dependabot.
    default_reviewers:
      - "yunpengn"
    default_labels:
      - "dependencies"
